version: '3'

services:
  # Laravel app service
  
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abiola78
      POSTGRES_DB: mydb

  client:
    image: harbiola/react-news-app:latest

